name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"   # runs daily at midnight
  workflow_dispatch:       # allow manual trigger

permissions:
  contents: write          # ✅ needed so the action can push changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate 3D profile contribution graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          username: rahulvijay007

      - name: Push 3D graph
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generated 3D contribution graph"
          add: "profile-3d-contrib/*"
